#'Removedor de Objetos/variáveis do ambiente.
#'
#'Script que remove as variáveis para que não ocorra conflitos no uso em dados agrupados.
#'
#'@param variaveis Indica um número referente ao conjunto de variáveis que será removida.
#'
#'@examples
#'removedor(variaveis)
#'
#'@export

removedor <- function(variaveis){
####################### FORD-WALFORD (1)
  if(variaveis == 1){
    rm(c_mais_um, envir = .GlobalEnv)
    rm(conjunto_ct, envir = .GlobalEnv)
    rm(contagem_idade, envir = .GlobalEnv)
    rm(contagem_total, envir = .GlobalEnv)
    rm(ct, envir = .GlobalEnv)
    rm(dados_ct, envir = .GlobalEnv)
    rm(dados_curva, envir = .GlobalEnv)
    rm(dadosDaIdade, envir = .GlobalEnv)
    rm(idade_log, envir = .GlobalEnv)
    rm(iidade, envir = .GlobalEnv)
    rm(log_c_infinito_menos_med_ct, envir = .GlobalEnv)
    rm(media_c, envir = .GlobalEnv)
    rm(c_a, envir = .GlobalEnv)
    rm(c_b, envir = .GlobalEnv)
    rm(c_infinito, envir = .GlobalEnv)
    rm(c_infinito_empirico, envir = .GlobalEnv)
    rm(ford, envir = .GlobalEnv)
    rm(k, envir = .GlobalEnv)
    rm(tzero, envir = .GlobalEnv)
    rm(ln_a, envir = .GlobalEnv)
    rm(ln_b, envir = .GlobalEnv)
    rm(ln_x, envir = .GlobalEnv)
    rm(ln_y, envir = .GlobalEnv)
    rm(r2_c, envir = .GlobalEnv)
    rm(r2_ln, envir = .GlobalEnv)
    rm(real_cont_total, envir = .GlobalEnv)
    rm(real_som_idade, envir = .GlobalEnv)
    return()
  }
####################### CURVA DE CRESCIMENTO (2)
  if(variaveis == 2){
    rm(dados_curva, envir = .GlobalEnv)
    rm(c_infinito, envir = .GlobalEnv)
    rm(respostaB, envir = .GlobalEnv)
    rm(respostaG, envir = .GlobalEnv)
    rm(respostaL, envir = .GlobalEnv)
    rm(curva_x, envir = .GlobalEnv)
    rm(curva_y, envir = .GlobalEnv)
    rm(curvayb, envir = .GlobalEnv)
    rm(curvayg, envir = .GlobalEnv)
    rm(curvayl, envir = .GlobalEnv)
    rm(k, envir = .GlobalEnv)
    rm(tzero, envir = .GlobalEnv)
    rm(real_cont_fw, envir = .GlobalEnv)
    rm(idades, envir = .GlobalEnv)
    rm(temporaria, envir = .GlobalEnv)
    return()
  }
####################### LEVENBERG-MARQUARDT (3)
  if(variaveis == 3){
    rm(vbl, envir = .GlobalEnv)
    rm(gom, envir = .GlobalEnv)
    rm(lgc, envir = .GlobalEnv)
    rm(vbl_extracao, envir = .GlobalEnv)
    rm(gom_extracao, envir = .GlobalEnv)
    rm(lgc_extracao, envir = .GlobalEnv)
    rm(cinfktzeroB, envir = .GlobalEnv)
    rm(cinfktzeroG, envir = .GlobalEnv)
    rm(cinfktzeroL, envir = .GlobalEnv)
    rm(c_infinito_ajustadoB, envir = .GlobalEnv)
    rm(c_infinito_ajustadoG, envir = .GlobalEnv)
    rm(c_infinito_ajustadoL, envir = .GlobalEnv)
    rm(curva_linha_ajustadaB, envir = .GlobalEnv)
    rm(curva_linha_ajustadaG, envir = .GlobalEnv)
    rm(curva_linha_ajustadaL, envir = .GlobalEnv)
    rm(k_ajustadoB, envir = .GlobalEnv)
    rm(k_ajustadoG, envir = .GlobalEnv)
    rm(k_ajustadoL, envir = .GlobalEnv)
    rm(tzero_ajustadoB, envir = .GlobalEnv)
    rm(tzero_ajustadoG, envir = .GlobalEnv)
    rm(tzero_ajustadoL, envir = .GlobalEnv)
    return()
  }
####################### IC (4)
  if(variaveis == 4){
    rm(sumarioB, envir = .GlobalEnv)
    rm(sumarioG, envir = .GlobalEnv)
    rm(sumarioL, envir = .GlobalEnv)
    rm(yB, envir = .GlobalEnv)
    rm(yG, envir = .GlobalEnv)
    rm(yL, envir = .GlobalEnv)
    rm(epB, envir = .GlobalEnv)
    rm(epG, envir = .GlobalEnv)
    rm(epL, envir = .GlobalEnv)
    rm(grausliberdade, envir = .GlobalEnv)
    rm(nivel, envir = .GlobalEnv)
    rm(raizN, envir = .GlobalEnv)
    rm(sdYB, envir = .GlobalEnv)
    rm(sdYG, envir = .GlobalEnv)
    rm(sdYL, envir = .GlobalEnv)
    rm(SyxB, envir = .GlobalEnv)
    rm(SyxG, envir = .GlobalEnv)
    rm(SyxL, envir = .GlobalEnv)
    rm(ta, envir = .GlobalEnv)
    rm(talfa, envir = .GlobalEnv)
    rm(media_yB, envir = .GlobalEnv)
    rm(media_yG, envir = .GlobalEnv)
    rm(media_yL, envir = .GlobalEnv)
    rm(y1B, envir = .GlobalEnv)
    rm(y1G, envir = .GlobalEnv)
    rm(y1L, envir = .GlobalEnv)
    rm(ymaiB, envir = .GlobalEnv)
    rm(ymaiG, envir = .GlobalEnv)
    rm(ymaiL, envir = .GlobalEnv)
    rm(ymeiB, envir = .GlobalEnv)
    rm(ymeiG, envir = .GlobalEnv)
    rm(ymeiL, envir = .GlobalEnv)
    return()
    }
####################### MORTALIDADE (5)
  if(variaveis == 5){
    rm(classe, envir = .GlobalEnv)
    rm(tamanho_bruto, envir = .GlobalEnv)
    rm(tamanho, envir = .GlobalEnv)
    rm(classes_ct, envir = .GlobalEnv)
    rm(dT, envir = .GlobalEnv)
    rm(limInf, envir = .GlobalEnv)
    rm(limSup, envir = .GlobalEnv)
    rm(LiN, envir = .GlobalEnv)
    rm(lnNdT, envir = .GlobalEnv)
    rm(tamClasse, envir = .GlobalEnv)
    rm(tAspas, envir = .GlobalEnv)
    rm(Ti, envir = .GlobalEnv)
    rm(acum, envir = .GlobalEnv)
    rm(agarraX, envir = .GlobalEnv)
    rm(agarraY, envir = .GlobalEnv)
    rm(conteReal, envir = .GlobalEnv)
    rm(contesReal, envir = .GlobalEnv)
    rm(contReal, envir = .GlobalEnv)
    rm(contRealX, envir = .GlobalEnv)
    rm(contRealY, envir = .GlobalEnv)
    rm(indiceClasseZ, envir = .GlobalEnv)
    rm(indiceD, envir = .GlobalEnv)
    rm(indiceI, envir = .GlobalEnv)
    rm(indiceJ, envir = .GlobalEnv)
    rm(lin, envir = .GlobalEnv)
    rm(ocultado, envir = .GlobalEnv)
    rm(n_tamanho_final, envir = .GlobalEnv)
    rm(respostaLimMin, envir = .GlobalEnv)
    rm(z_x, envir = .GlobalEnv)
    rm(z_xx, envir = .GlobalEnv)
    rm(z_y, envir = .GlobalEnv)
    rm(z_yy, envir = .GlobalEnv)
    rm(z_a, envir = .GlobalEnv)
    rm(z_b, envir = .GlobalEnv)
    rm(r2_z, envir = .GlobalEnv)
    return()
  }

  ####################### MORTALIDADE (51)
  if(variaveis == 51){
    rm(classe, envir = .GlobalEnv)
    rm(tamanho_bruto, envir = .GlobalEnv)
    rm(tamanho, envir = .GlobalEnv)
    rm(classes_ct, envir = .GlobalEnv)
    rm(dT, envir = .GlobalEnv)
    rm(limInf, envir = .GlobalEnv)
    rm(limSup, envir = .GlobalEnv)
    rm(LiN, envir = .GlobalEnv)
    rm(lnNdT, envir = .GlobalEnv)
    rm(tamClasse, envir = .GlobalEnv)
    rm(tAspas, envir = .GlobalEnv)
    rm(Ti, envir = .GlobalEnv)
    rm(acum, envir = .GlobalEnv)
    rm(agarraX, envir = .GlobalEnv)
    rm(agarraY, envir = .GlobalEnv)
    rm(conteReal, envir = .GlobalEnv)
    rm(contesReal, envir = .GlobalEnv)
    rm(contReal, envir = .GlobalEnv)
    rm(contRealX, envir = .GlobalEnv)
    rm(contRealY, envir = .GlobalEnv)
    rm(indiceClasseZ, envir = .GlobalEnv)
    rm(indiceD, envir = .GlobalEnv)
    rm(indiceI, envir = .GlobalEnv)
    rm(indiceJ, envir = .GlobalEnv)
    rm(lin, envir = .GlobalEnv)
    rm(ocultado, envir = .GlobalEnv)
    rm(n_tamanho, envir = .GlobalEnv)
    rm(respostaLimMin, envir = .GlobalEnv)
    rm(z_x, envir = .GlobalEnv)
    rm(z_xx, envir = .GlobalEnv)
    rm(z_y, envir = .GlobalEnv)
    rm(z_yy, envir = .GlobalEnv)
    rm(z_a, envir = .GlobalEnv)
    rm(z_b, envir = .GlobalEnv)
    rm(r2_z, envir = .GlobalEnv)
    return()
  }
####################### MORTALIDADE TOTAL IDADES (52)
  if(variaveis == 52){
    rm(Z, envir = .GlobalEnv)
    rm(tAspas, envir = .GlobalEnv)
    rm(phi, envir = .GlobalEnv)
    rm(M, envir = .GlobalEnv)
    return()
  }
  
####################### REMOVEDOR DE OUTLIERS (6)
  if(variaveis == 6){
    rm(filtro, envir = .GlobalEnv)
    rm(analisar, envir = .GlobalEnv)
    rm(quartil, envir = .GlobalEnv)
    rm(quartil1, envir = .GlobalEnv)
    rm(quartil3, envir = .GlobalEnv)
    rm(i_qr, envir = .GlobalEnv)
    rm(L_sup, envir = .GlobalEnv)
    rm(L_inf, envir = .GlobalEnv)
    rm(contagem, envir = .GlobalEnv)
    rm(ene, envir = .GlobalEnv)
    rm(x, envir = .GlobalEnv)
    rm(y, envir = .GlobalEnv)
    rm(dadosIdade, envir = .GlobalEnv)
    rm(dadosVelho, envir = .GlobalEnv)
    rm(idadeOrdenada, envir = .GlobalEnv)
    rm(contagemIdade, envir = .GlobalEnv)
    rm(Nidade, envir = .GlobalEnv)
    rm(media, envir = .GlobalEnv)
    rm(somatorioIdade, envir = .GlobalEnv)
    return()
  }

####################### GERAL SEM GRUPO (7)
  if(variaveis == 7){
    rm(c_mais_um, envir = .GlobalEnv)
    rm(classe_ct_bruto, envir = .GlobalEnv)
    rm(classes_ct, envir = .GlobalEnv)
    rm(classess_ct, envir = .GlobalEnv)
    rm(conjunto_ct, envir = .GlobalEnv)
    rm(ct, envir = .GlobalEnv)
    rm(dados_ct, envir = .GlobalEnv)
    rm(dados_curva, envir = .GlobalEnv)
    rm(dados_curvaS, envir = .GlobalEnv)
    rm(dT, envir = .GlobalEnv)
    rm(gom, envir = .GlobalEnv)
    rm(gom_extracao, envir = .GlobalEnv)
    rm(idade_log, envir = .GlobalEnv)
    rm(lgc, envir = .GlobalEnv)
    rm(lgc_extracao, envir = .GlobalEnv)
    rm(LiN, envir = .GlobalEnv)
    rm(lin, envir = .GlobalEnv)
    rm(lnNdT, envir = .GlobalEnv)
    rm(log_c_infinito_menos_med_ct, envir = .GlobalEnv)
    rm(media_c, envir = .GlobalEnv)
    rm(sumarioB, envir = .GlobalEnv)
    rm(sumarioG, envir = .GlobalEnv)
    rm(sumarioL, envir = .GlobalEnv)
    rm(tAspas, envir = .GlobalEnv)
    rm(Ti, envir = .GlobalEnv)
    rm(vbl, envir = .GlobalEnv)
    rm(vbl_extracao, envir = .GlobalEnv)
    rm(yB, envir = .GlobalEnv)
    rm(yG, envir = .GlobalEnv)
    rm(yL, envir = .GlobalEnv)
    rm(acum, envir = .GlobalEnv)
    rm(agarraX, envir = .GlobalEnv)
    rm(agarraY, envir = .GlobalEnv)
    #rm(buscaErro, envir = .GlobalEnv)
    rm(temporaria, envir = .GlobalEnv)
    rm(c_a, envir = .GlobalEnv)
    rm(c_b, envir = .GlobalEnv)
    rm(c_infinito, envir = .GlobalEnv)
    rm(c_infinito_ajustadoB, envir = .GlobalEnv)
    rm(c_infinito_ajustadoG, envir = .GlobalEnv)
    rm(c_infinito_ajustadoL, envir = .GlobalEnv)
    rm(c_infinito_empirico, envir = .GlobalEnv)
    rm(classe, envir = .GlobalEnv)
    rm(contagem_fw, envir = .GlobalEnv)
    rm(contagem_idade, envir = .GlobalEnv)
    rm(contagem_total, envir = .GlobalEnv)
    rm(conteReal, envir = .GlobalEnv)
    rm(contesReal, envir = .GlobalEnv)
    rm(contReal, envir = .GlobalEnv)
    rm(contRealX, envir = .GlobalEnv)
    rm(contRealY, envir = .GlobalEnv)
    rm(curva_linha_ajustadaB, envir = .GlobalEnv)
    rm(curva_linha_ajustadaG, envir = .GlobalEnv)
    rm(curva_linha_ajustadaL, envir = .GlobalEnv)
    rm(curvayb, envir = .GlobalEnv)
    rm(curvayg, envir = .GlobalEnv)
    rm(curvayl, envir = .GlobalEnv)
    rm(curva_x, envir = .GlobalEnv)
    rm(curva_y, envir = .GlobalEnv)
    rm(dadosDaIdade, envir = .GlobalEnv)
    rm(epB, envir = .GlobalEnv)
    rm(epG, envir = .GlobalEnv)
    rm(epL, envir = .GlobalEnv)
    rm(erro, envir = .GlobalEnv)
    rm(grausliberdade, envir = .GlobalEnv)
    rm(iidade, envir = .GlobalEnv)
    rm(indiceClasseZ, envir = .GlobalEnv)
    rm(indiceD, envir = .GlobalEnv)
    rm(indiceI, envir = .GlobalEnv)
    rm(indiceJ, envir = .GlobalEnv)
    rm(k, envir = .GlobalEnv)
    rm(k_ajustadoB, envir = .GlobalEnv)
    rm(k_ajustadoG, envir = .GlobalEnv)
    rm(k_ajustadoL, envir = .GlobalEnv)
    rm(limInf, envir = .GlobalEnv)
    rm(limSup, envir = .GlobalEnv)
    rm(ln_a, envir = .GlobalEnv)
    rm(ln_b, envir = .GlobalEnv)
    rm(ln_x, envir = .GlobalEnv)
    rm(ln_y, envir = .GlobalEnv)
    rm(media_yB, envir = .GlobalEnv)
    rm(media_yG, envir = .GlobalEnv)
    rm(media_yL, envir = .GlobalEnv)
    rm(nivel, envir = .GlobalEnv)
    #rm(Nln, envir = .GlobalEnv)
    rm(ocultado, envir = .GlobalEnv)
    rm(r2_c, envir = .GlobalEnv)
    rm(r2_ln, envir = .GlobalEnv)
    rm(r2_z, envir = .GlobalEnv)
    rm(raizN, envir = .GlobalEnv)
    rm(real_cont_fw, envir = .GlobalEnv)
    rm(real_cont_fww, envir = .GlobalEnv)
    rm(real_cont_total, envir = .GlobalEnv)
    rm(real_som_idade, envir = .GlobalEnv)
    #rm(respostaAdulterio, envir = .GlobalEnv)
    rm(respostaAjuste, envir = .GlobalEnv)
    rm(respostaB, envir = .GlobalEnv)
    rm(respostaCurvas, envir = .GlobalEnv)
    rm(respostaCurvasAjustadas, envir = .GlobalEnv)
    rm(respostaG, envir = .GlobalEnv)
    rm(respostaL, envir = .GlobalEnv)
    rm(respostaLimMin, envir = .GlobalEnv)
    #rm(respostaMorta, envir = .GlobalEnv)
    rm(sdYB, envir = .GlobalEnv)
    rm(sdYG, envir = .GlobalEnv)
    rm(sdYL, envir = .GlobalEnv)
    rm(sexo, envir = .GlobalEnv)
    rm(SyxB, envir = .GlobalEnv)
    rm(SyxG, envir = .GlobalEnv)
    rm(SyxL, envir = .GlobalEnv)
    rm(ta, envir = .GlobalEnv)
    rm(talfa, envir = .GlobalEnv)
    rm(tamClasse, envir = .GlobalEnv)
    rm(tzero, envir = .GlobalEnv)
    rm(tzero_ajustadoB, envir = .GlobalEnv)
    rm(tzero_ajustadoG, envir = .GlobalEnv)
    rm(tzero_ajustadoL, envir = .GlobalEnv)
    rm(y1B, envir = .GlobalEnv)
    rm(y1G, envir = .GlobalEnv)
    rm(y1L, envir = .GlobalEnv)
    rm(ymaiB, envir = .GlobalEnv)
    rm(ymaiG, envir = .GlobalEnv)
    rm(ymaiL, envir = .GlobalEnv)
    rm(ymeiB, envir = .GlobalEnv)
    rm(ymeiG, envir = .GlobalEnv)
    rm(ymeiL, envir = .GlobalEnv)
    rm(z_a, envir = .GlobalEnv)
    rm(z_b, envir = .GlobalEnv)
    rm(z_x, envir = .GlobalEnv)
    rm(z_xx, envir = .GlobalEnv)
    rm(z_y, envir = .GlobalEnv)
    rm(z_yy, envir = .GlobalEnv)
    rm(buscaErro, envir = .GlobalEnv)
    rm(coresA, envir = .GlobalEnv)
    rm(coresB, envir = .GlobalEnv)
    rm(coresC, envir = .GlobalEnv)
    rm(coresD, envir = .GlobalEnv)
    rm(coresE, envir = .GlobalEnv)
    rm(coresF, envir = .GlobalEnv)
    rm(coresG, envir = .GlobalEnv)
    rm(corPontoA, envir = .GlobalEnv)
    rm(corPontoB, envir = .GlobalEnv)
    rm(corPontoC, envir = .GlobalEnv)
    rm(corPontoD, envir = .GlobalEnv)
    rm(corPontoE, envir = .GlobalEnv)
    rm(limX, envir = .GlobalEnv)
    rm(limY, envir = .GlobalEnv)
    rm(limY, envir = .GlobalEnv)
    rm(modeloA, envir = .GlobalEnv)
    rm(modeloB, envir = .GlobalEnv)
    rm(modeloC, envir = .GlobalEnv)
    rm(modeloD, envir = .GlobalEnv)
    rm(modelOld, envir = .GlobalEnv)
    rm(ok, envir = .GlobalEnv)
    rm(tipoCaixaA, envir = .GlobalEnv)
    rm(tipoCaixaAA, envir = .GlobalEnv)
    rm(tipoCaixaB, envir = .GlobalEnv)
    rm(tipoCaixaBB, envir = .GlobalEnv)
    rm(tipoCaixaC, envir = .GlobalEnv)
    rm(tipoCaixaCC, envir = .GlobalEnv)
    rm(tipoCaixaD, envir = .GlobalEnv)
    rm(tipoCaixaDD, envir = .GlobalEnv)
    rm(tipoCaixaE, envir = .GlobalEnv)
    rm(tipoCaixaEE, envir = .GlobalEnv)
    rm(tipoLinhaA, envir = .GlobalEnv)
    rm(tipoLinhaAA, envir = .GlobalEnv)
    rm(tipoLinhaB, envir = .GlobalEnv)
    rm(tipoLinhaBB, envir = .GlobalEnv)
    rm(tipoLinhaC, envir = .GlobalEnv)
    rm(tipoLinhaCC, envir = .GlobalEnv)
    rm(tipoLinhaD, envir = .GlobalEnv)
    rm(respostaGraficos, envir = .GlobalEnv)
    return()
  }
  ####################### GERAL COM GRUPO (8)
  if(variaveis == 8){
    rm(buscaErro, envir = .GlobalEnv)
    rm(c_infinito_ajustadoBF, envir = .GlobalEnv)
    rm(c_infinito_ajustadoBM, envir = .GlobalEnv)
    rm(c_infinito_ajustadoGF, envir = .GlobalEnv)
    rm(c_infinito_ajustadoGM, envir = .GlobalEnv)
    rm(c_infinito_ajustadoLF, envir = .GlobalEnv)
    rm(c_infinito_ajustadoLM, envir = .GlobalEnv)
    rm(c_infinitoF, envir = .GlobalEnv)
    rm(c_infinitoM, envir = .GlobalEnv)
    rm(coresA, envir = .GlobalEnv)
    rm(coresB, envir = .GlobalEnv)
    rm(coresC, envir = .GlobalEnv)
    rm(coresD, envir = .GlobalEnv)
    rm(coresE, envir = .GlobalEnv)
    rm(coresF, envir = .GlobalEnv)
    rm(coresG, envir = .GlobalEnv)
    rm(corPontoA, envir = .GlobalEnv)
    rm(corPontoB, envir = .GlobalEnv)
    rm(corPontoC, envir = .GlobalEnv)
    rm(corPontoD, envir = .GlobalEnv)
    rm(corPontoE, envir = .GlobalEnv)
    rm(k_ajustadoBF, envir = .GlobalEnv)
    rm(k_ajustadoBM, envir = .GlobalEnv)
    rm(k_ajustadoGF, envir = .GlobalEnv)
    rm(k_ajustadoGM, envir = .GlobalEnv)
    rm(k_ajustadoLF, envir = .GlobalEnv)
    rm(k_ajustadoLM, envir = .GlobalEnv)
    rm(kF, envir = .GlobalEnv)
    rm(kM, envir = .GlobalEnv)
    rm(limX, envir = .GlobalEnv)
    rm(limY, envir = .GlobalEnv)
    rm(modeloA, envir = .GlobalEnv)
    rm(modeloB, envir = .GlobalEnv)
    rm(modeloC, envir = .GlobalEnv)
    rm(modeloD, envir = .GlobalEnv)
    rm(modelOld, envir = .GlobalEnv)
    rm(ok, envir = .GlobalEnv)
    rm(tipoCaixaA, envir = .GlobalEnv)
    rm(tipoCaixaAA, envir = .GlobalEnv)
    rm(tipoCaixaB, envir = .GlobalEnv)
    rm(tipoCaixaBB, envir = .GlobalEnv)
    rm(tipoCaixaC, envir = .GlobalEnv)
    rm(tipoCaixaCC, envir = .GlobalEnv)
    rm(tipoCaixaD, envir = .GlobalEnv)
    rm(tipoCaixaDD, envir = .GlobalEnv)
    rm(tipoCaixaE, envir = .GlobalEnv)
    rm(tipoCaixaEE, envir = .GlobalEnv)
    rm(tipoLinhaA, envir = .GlobalEnv)
    rm(tipoLinhaAA, envir = .GlobalEnv)
    rm(tipoLinhaB, envir = .GlobalEnv)
    rm(tipoLinhaBB, envir = .GlobalEnv)
    rm(tipoLinhaC, envir = .GlobalEnv)
    rm(tipoLinhaCC, envir = .GlobalEnv)
    rm(tipoLinhaD, envir = .GlobalEnv)
    rm(tzero_ajustadoBF, envir = .GlobalEnv)
    rm(tzero_ajustadoBM, envir = .GlobalEnv)
    rm(tzero_ajustadoGF, envir = .GlobalEnv)
    rm(tzero_ajustadoGM, envir = .GlobalEnv)
    rm(tzero_ajustadoLF, envir = .GlobalEnv)
    rm(tzero_ajustadoLM, envir = .GlobalEnv)
    rm(tzeroF, envir = .GlobalEnv)
    rm(tzeroM, envir = .GlobalEnv)
    rm(respostaGraficos, envir = .GlobalEnv)
    rm(contagem_fwB, envir = .GlobalEnv)
    rm(contagem_fwA, envir = .GlobalEnv)
    rm(dados_curvaF, envir = .GlobalEnv)
    rm(dados_curvaM, envir = .GlobalEnv)
    return()
  }



  }
